### ISSUE TITLE
Suggestion: Clicking an entry in history should fill UI with the request

### ISSUE THREAD

**Issue by SAPikachu** [REST-API-Client/API-Client-VSCode-Extension#41]
This is a more expected behavior instead of sending the request directly. Thank you for the extension by the way. :)

**Comment by unwls** [comment]
Hey **@SAPikachu** 

Thank you very much for dropping by for a suggestion! 😊

This really is indeed a nice suggestion and I'm very positive about it. 

I will try to implement this feature when I have some time available (currently studying technical interview questions for my first job).

Wishing you a wonderful day,
Jin

**Comment by unwls** [comment]
@SAPikachu Thanks for the idea! 

Just pushed this new feature update to the VSCode extension marketplace.

This new feature should be available to history collections added from today onwards! 🚀
