### ISSUE TITLE
POST body is converted to JSON string before sending to server

### ISSUE THREAD

**Issue by SAPikachu** [REST-API-Client/API-Client-VSCode-Extension#42]
Attached a sample test request.

![image](https://user-images.githubusercontent.com/653824/182511782-ff371555-0f2a-4ba8-8a78-e012454d00e1.png)

**Comment by unwls** [comment]
@SAPikachu 

Oh no.. haha
I'll have a look into this problem! 

Thank's for taking your time reporting bugs 🐛
bugs should be eliminated asap!!!

Best Regards,
Jin

**Comment by unwls** [comment]
@SAPikachu 

Thanks for your feedback! I found the bug, I was unnecessarily transforming Raw Data to string using `JSON.stringify` before sending it to server :/

Wouldn't have found this bug without the community!

I just pushed a new update :) 

Thanks again and have a good evening/day ☺️
