### ISSUE TITLE
Good first issue ideas 🚀

### ISSUE THREAD

**Issue by unwls** [REST-API-Client/API-Client-VSCode-Extension#48]
If anybody is interested in contributing, I have some ideas which could get you started! 

1. ~~Webview request panel UI gets automatically filled up when the request from collection sidebar is sent~~
2. Button to change the webview panel view into side by side
3. Feature to send a GraphQL request would be a decent starting point.
4. More options when sending post requests
5. ~~Feature to automatically fill key, value tables when JSON file is uploaded (could be params or headers)~~ [sergptz](https://github.com/sergptz)
6. Feature to send non-string data's when sending request

Feel free to drop by a comment with any questions regarding the project! ☺️

**Comment by chiizzy1** [comment]
Hi there!
I'd love to contribute but I'm new to open source, how do I go about it?

**Comment by unwls** [comment]
Hey @chiizzy1
Thanks for dropping by, I appreciate your interest in contributing 🚀

Im open to any ideas or suggestions that could improve my current vscode extension so you can look over my code and really put your magic into it! 

I'll write down a detailed guide on how you can get started, once you open a pull request with your code, i'll review it and merge it. Once it's merged, ill make sure to add you on the contributors list! 

### Detailed Guide to starting coding
1. Fork this Project from [here](https://github.com/REST-API-Client/API-Client-VSCode-Extension)
2. Create your Branch &#8594; `git checkout -b feature/newFeature`
3. Code up your outstanding logic &#8594; `console.log("Hello World")`
4. Commit your Changes &#8594; `git commit -m "feat: Add some newFeature"`
5. Push to the Branch &#8594; `push changes to your forked repository and make a pull request`
6. Vist your GitHub repository and open a Pull Request

#### 🏗 Running the extension locally for development

1. Run `git clone` from this [repository](https://github.com/REST-API-Client/API-Client-VSCode-Extension)
2. Run npm install in order to install all the dependencies needed
3. Press F5 to launch extension development mode

**Comment by Cxxshyy** [comment]
Hi i sent you an email before how would i go about doing number 3 with graph ql

**Comment by unwls** [comment]
Hey @Cxxshyy ! Thanks for your interest in my project. 🚀

I'm assuming you know how to use GraphQL, my suggestion for you is to take a look at postman UI since my project is very similar to postman UI/UX.

### Postman

<img width="800" alt="Postman API Client" src="https://user-images.githubusercontent.com/83770081/192121359-027491a7-557e-47f6-90b2-5b8d986b0271.png">

### REST API Client
<img width="800" alt="REST API Client" src="https://user-images.githubusercontent.com/83770081/192121574-c0e219cf-d710-49ec-b26e-7b3bc75c1a71.png">

### A brief introduction to the folder structure
`src` directory contains Extension Host logic
`webview` directory contains react logic(what is being displayed to the user)

You could start by adding the GraphQL option on the request section of the Webview panel and use CodeEditor component which I have implemented but this is up to you.
I'm not enforcing you to reuse my component, feel free to implement your own but it would be nice if you could reuse my component. 

Once the user sends the request with GraphQL data, all the data goes to Extension Host logic which is inside `src/MainWebviewPanel.js` directory. 


It processes http request logic and sends it back to the Webview panel.

[This documentation could help you understand my extension data flow](https://code.visualstudio.com/api/extension-guides/webview#scripts-and-message-passing)

Regarding how to get you started, I suggest you take a look at my previous comment in this issue thread ☺️

Feel free to ask me any questions and good luck! 🚀

**Comment by Cxxshyy** [comment]
Hi dumb question but is there a way i can run this and update the code and see it live like with a website with react for example.

**Comment by unwls** [comment]
@Cxxshyy 

When I was building this extension, I had to refresh the Webview everytime I make a change with VSCode command `>Developer: Reload Window` but if you happen to find a better way feel free to add that command for future contributors.

But manually refreshing everytime is a pain...

[This video(44:13 ~ 49:25)](https://www.youtube.com/watch?v=a5DX5pQ9p5M&t=2453s&ab_channel=BenAwad) won't answer your question but I'm guessing this is a decent pattern

**Comment by Cxxshyy** [comment]
@unwls ok thanks

**Comment by Cxxshyy** [comment]
@unwls extension wont run for me at the moment keep getting error related to deprecation and 
![image](https://user-images.githubusercontent.com/74113508/192268356-37778e80-37ee-4636-9ce1-6df4bb1ba40e.png)
stuff like this

**Comment by unwls** [comment]
@Cxxshyy That's weird, is it giving an error after your changes or when you ran locally after git clone?

**Comment by Cxxshyy** [comment]
@unwls haven't made any changes yet. I had tried running locally through git clone after reading the codebase

**Comment by unwls** [comment]
@Cxxshyy Have you tried running VSCode Extension development mode(F5) on webpack development mode?

Webpack Development Mode - `npm run webpack-dev` and then press `F5` to enter Extension development mode

**Comment by Cxxshyy** [comment]
@unwls Yeah this worked thanks I don't know what was up with it.

**Comment by Cxxshyy** [comment]
@unwls also for the code snippet I assume its related to my vscode theme but the languages aren't visible unless hovered over so maybe something to implement to fix that.
![image](https://user-images.githubusercontent.com/74113508/192357968-25f99041-dde9-4fbc-b2c4-683c26d832f4.png)

**Comment by unwls** [comment]
@Cxxshyy Right...  Thanks for pointing out this issue. 👍

That's probably because I didn't code the colour of texts inside the option to match different VSCode themes. 

If you do want to get involved and fix that issue, I believe you can use certain CSS to match various VSCode themes. 

```
a {
  color: var(--vscode-textLink-foreground);
}
```
[This CSS code from Microsoft VSCode extension example](https://github.com/microsoft/vscode-extension-samples/blob/main/webview-sample/media/vscode.css) might give you some idea.

**Comment by Cxxshyy** [comment]
@unwls Yeah ill do that right now and raise a pr to fix that issue.

**Comment by unwls** [comment]
@Cxxshyy Sounds good! 🚀

**Comment by sergptz** [comment]
Hey there!
I've added a [pull request for #5](https://github.com/REST-API-Client/API-Client-VSCode-Extension/pull/53) (loading data from JSON files).
Check it out please :)

**Comment by unwls** [comment]
@sergptz Awesome! Will check it out right away 🚀

**Comment by sergptz** [comment]
Hey there @unwls !

Could you please give me more details on #2, #4 and #6?
#2 - What do "webview panel" and "side-by-side" view mean? How can I switch between those view modes to see the difference? Or on of these view modes must be implemented at first?
#4 - What options are needed to be added?
#6 - What data types are needed?

**Comment by unwls** [comment]
@sergptz
#2 Would be nice if the layout of the extension changed. I won't give any specific directions regarding the layout but if your layout is nice, why not apply it?

#4 Currently, there's only 5 methods to send requests, but a few more could be added!

#6 Something like images? that would be cool!

**Comment by unwls** [comment]
Opening new good first issue post since this ones stale
