### ISSUE TITLE
Implementing Graphql option 

### ISSUE THREAD

**Issue by Cxxshyy** [REST-API-Client/API-Client-VSCode-Extension#51]
just opening an issue to discuss about the upcoming PR

**Comment by Cxxshyy** [comment]
![image](https://user-images.githubusercontent.com/74113508/193009534-0b425977-13e6-4d4b-91e4-2781b0f0bfc1.png)
added the option as of now but going to be implementing functionality soon

**Comment by Cxxshyy** [comment]
![image](https://user-images.githubusercontent.com/74113508/193009728-fbe25cca-589f-4cf0-b6b3-b4f0907e8770.png)
added the option as of now and will add functionality soon

**Comment by unwls** [comment]
Looks good to me! Ill merge your previous PR asap

**Comment by unwls** [comment]
Closing this issue since it's stale
