### ISSUE TITLE
Extension Activation failed (Locally)

### ISSUE THREAD

**Issue by AhmedEl-Gazzar** [REST-API-Client/API-Client-VSCode-Extension#52]
Hi, 
I was attempting to run the extension locally and received the following message:
`Activating extension 'unjinjang.rest-api-client' failed: Cannot find module '.../API-Client-VSCode-Extension/dist/extension.js' Require stack: - /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.`

I followed the instructions on the README.

What should I do to fix this issue?

**Comment by unwls** [comment]
Hey! 

Have you tried running VSCode Extension development mode(F5) on webpack development mode?

Webpack Development Mode - `npm run webpack-dev` and then press F5 to enter Extension development mode

**Comment by unwls** [comment]
Closing this issue since it's stale
