### ISSUE TITLE
[DOC] Update Contributors in README to use Github Contributions

### ISSUE THREAD

**Issue by 0necontroller** [REST-API-Client/API-Client-VSCode-Extension#55]
Hello, I found interest🚀 in your project and I really want to contribute.\
This is the first and  I hope it positively impacts your project. Looking
forward to more contributions🫧.

### Changes made🏗:

- [x]  Updated table of content with sub lists.
- [x] Updated .gitIgnore to .gitignore
- [x] Updated Contributors section👇 .

## 🫧 Contributors 
[![Contributors](https://contrib.rocks/image?repo=REST-API-Client/API-Client-VSCode-Extension)](https://github.com/REST-API-Client/API-Client-VSCode-Extension/graphs/contributors)
-  [Unjin Jang](https://github.com/unwls)
-  [Cxxshyy](https://github.com/Cxxshyy)
-  [sergptz](https://github.com/sergptz)

**Comment by unwls** [comment]
Fantastic! Thanks for this contribution and sorry for a very late response :)

Will check your pr and merge it!
