### ISSUE TITLE
Button to change the webview panel view into side by side 

### ISSUE THREAD

**Issue by unwls** [REST-API-Client/API-Client-VSCode-Extension#64]
1. Button to change the webview panel view into side by side - @Shubh8899

**Comment by Shubh8899** [comment]
I am interested in contributing & would like to know more about point 1.

**Comment by unwls** [comment]
Hey @Shubh8899! 

Below GIF is the current UI

### Current UI
![Animation](https://user-images.githubusercontent.com/83770081/235853922-66d7581b-eb79-49fa-a451-4773422e9d45.gif)


You could try to make it like below where it moves from side to side. That's my suggestion but you can make it however you want!

### LeetCode View Panel UI
![chrome-capture-2023-4-3](https://user-images.githubusercontent.com/83770081/235853180-9e904194-16fa-41a8-b5d8-03fa2634edee.gif)

**Comment by Shubh8899** [comment]
Okay got it. Your suggestion seems good, i will start working on it. Can you assign the issue to me?

**Comment by unwls** [comment]
@Shubh8899 All done! Good luck!!

**Comment by unwls** [comment]
@Shubh8899 Any updates? I'm planning to close this issue since its statle.

**Comment by Shubh8899** [comment]
I am not available this week hence i won't be able to continue. Apologies for inconvenience, you can unassign me.

**Comment by unwls** [comment]
@Shubh8899 Sounds good! No worries :)
